apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: cassandrarest
  name: cassandrarest-controller
spec:
  replicas: 1
  selector:
    component: cassandrarest
  template:
    metadata:
      labels:
        app: cassandrarestapp
        component: cassandrarest
    spec:
      containers:
      - image: joeygibson/cassandrarest
        name: cassandrarest
        ports:
        - containerPort: 3000
          hostPort: 3000
        resources:
          limits:
            cpu: 100m
